apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-check
  namespace: project
spec:
  metrics:
  - name: cpu-usage
    interval: 1m
    successCondition: result < 0.5
    failureLimit: 1
    provider:
      prometheus:
        # Ersetze dies durch deinen Prometheus-Service-DNS (findest du mit kubectl get svc -n prometheus)
        address: http://prometheus-stack-kube-prom-prometheus.prometheus.svc.cluster.local:9090
        query: |
          sum(rate(container_cpu_usage_seconds_total{namespace="project"}[5m]))
