apiVersion: v1
kind: Pod
metadata:
  name: wikipedia-server
spec:
  volumes: [{name: html, emptyDir: {}}]
  initContainers:
  - name: init-wiki
    image: curlimages/curl
    args: ["-o", "/data/index.html", "https://en.wikipedia.org/wiki/Kubernetes"]
    volumeMounts: [{name: html, mountPath: /data}]
  containers:
  - name: nginx
    image: nginx
    volumeMounts: [{name: html, mountPath: /usr/share/nginx/html}]
  - name: sidecar
    image: curlimages/curl
    command: ["sh", "-c", "while true; do sleep 600; curl -L https://en.wikipedia.org/wiki/Special:Random -o /data/index.html; done"]
    volumeMounts: [{name: html, mountPath: /data}]