apiVersion: v1
kind: Pod
metadata:
  name: wikipedia-server
spec:
  volumes: [{name: html, emptyDir: {}}]
  initContainers:
  - name: init-wiki
    image: curlimages/curl
    command: ["/bin/sh", "-c", "curl https://en.wikipedia.org/wiki/Kubernetes > /usr/share/nginx/html/index.html"]
    volumeMounts: [{name: html, mountPath: /usr/share/nginx/html}]
  containers:
  - name: nginx
    image: nginx
    volumeMounts: [{name: html, mountPath: /usr/share/nginx/html}]
  - name: sidecar
    image: curlimages/curl
    command: ["/bin/sh", "-c", "while true; do sleep 900; curl https://en.wikipedia.org/wiki/Special:Random > /usr/share/nginx/html/index.html; done"]
    volumeMounts: [{name: html, mountPath: /usr/share/nginx/html}]