apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: google/cloud-sdk:slim
            command: ["sh", "-c", "pg_dump $URL | gsutil cp - gs://your-bucket-name/backup.sql"]
