apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-check
spec:
  metrics:
  - name: cpu-rate
    interval: 1m
    count: 5
    provider:
      prometheus:
        address: http://prometheus:9090
        query: sum(rate(container_cpu_usage_seconds_total[5m]))
