apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
spec:
  replicas: 6
  template:
    spec:
      containers:
      - name: broadcaster
        image: oezkan00/broadcaster:latest
        env:
        - name: NATS_QUEUE_GROUP
          value: "broadcaster-group"
